### ISSUE TITLE
不支持null

### ISSUE THREAD

**Issue by czlc** [lvzixun/ljson#2]
{"name": null } 会解析报错

**Comment by czlc** [comment]
map   = P"{" \* pass \*  _gen_entry(entry) \* pass \* E"}" / 
    function (...)
        local t = _gen_table(...)
        local ret = {}
        assert(#t%2 == 0)   /\* 猜测null对应于nil，所以#t并没有反应需要的元素个数 */
        for i=1, #t, 2 do
          local k = t[i]
          local v = t[i+1]
          ret[k] = v
        end
        return ret
    end,

**Comment by lvzixun** [comment]
这份代码是我两年前想玩下`Lpeg`，当时想来想去就实现了json解析库了。 json的官方测试用例并没有完全覆盖。所以出现bug应该是很正常的，这两天我再重构下吧  ；）

**Comment by czlc** [comment]
赞
